@API_HostAddress = http://localhost:5181

### 🔹 Get All Employees
GET {{API_HostAddress}}/api/employees
Accept: application/json


### Get All Departments
GET {{API_HostAddress}}/api/departments
Accept: application/json

### Post Employee With Projects
POST {{API_HostAddress}}/api/employees
Accept: application/json
Content-Type: application/json

{
  "name": "Abbas",
  "salary": 7200,
  "departmentId": 1,
  "projectIds": [1, 2]
}